# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

defaults:
  run:
    working-directory: base-test-api

jobs:
  build:

    runs-on: ubuntu-latest
    environment: Production

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.6
      uses: actions/setup-python@v3
      with:
        python-version: "3.6"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pipenv
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pipenv install ;
        BASE_API_ENV=test pipenv run pytest

    - name: Login to DockerHub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_USERNAME }}
        password: ${{ secrets.DOCKER_PASSWORD }}

    - name: Extract metadata (tags, labels) for Docker
      id: meta
      uses: docker/metadata-action@v3
      with:
        images: rossijonas/desafio-devops
        tags: |
          type=ref,event=branch
          type=sha
          type=sha,prefix={{branch}}-
          type=sha,format=long
          type=sha,format=long,prefix={{branch}}-
          type=raw,value=latest

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        context: .
        file: Dockerfile
        push: true
        tags: ${{ steps.meta.outputs.tags }}
        labels: ${{ steps.meta.outputs.labels }}
